name: snipsyncs
description: A professional salon booking system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  provider: ^6.1.1
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true